# Generated by Django 5.0 on 2024-01-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodscat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='slug',
            field=models.SlugField(default='#', max_length=255),
        ),
    ]
