# Generated by Django 5.0 on 2024-01-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodscat', '0002_goods_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
