# Generated by Django 5.0 on 2024-01-13 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodscat', '0003_alter_goods_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='goodscat.category'),
        ),
    ]
