# Generated by Django 5.0 on 2024-01-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodscat', '0006_tagpost_goods_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'DRAFT'), (1, 'PUBLISHED')], default=1),
        ),
    ]
